version: '3'

services:

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
      
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: zuvaLabs

  # mq:
  #   image: rabbitmq:3.12-management
  #   restart: unless-stopped
  #   ports:
  #     - 5672:5672  # RabbitMQ default port
  #     - 15672:15672  # RabbitMQ management console port
  #     - 15674:15674  # RabbitMQ STOMP port

  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq  # Persist data
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=root  # Set the desired username
  #     - RABBITMQ_DEFAULT_PASS=zuvaLabs  # Set the desired password
  #     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management
  #     - RABBITMQ_PLUGINS=rabbitmq_web_stomp

  backend:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
    # volumes:
    #   - .:/usr/src/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - mongodb
      # - mq
    environment:
      - MONGO_HOST=lab.zuvatech.com
      - MONGO_PORT=27017

  socket:
    build: .
    command: uvicorn socketio_manager.main:app --reload --port 9000 --host 0.0.0.0
    # volumes:
    # volumes:
    #   - .:/usr/src/app
    ports:
      - "9003:9000"
    # depends_on:
    #   - mongodb
      # - mq
    environment:
      - MONGO_HOST=lab.zuvatech.com
      - MONGO_PORT=27017

volumes:
  mongo_data:
  rabbitmq_data:
