version: "3.8"

services:

  backend_salary_management:
      build:
        context: ..
        dockerfile: app/Dockerfile
      hostname: backend_salary_management
      container_name: backend_salary_management
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend_salary_management.rule=Host(`backend_salary_management.localhost`)"
        - "traefik.http.services.backend_salary_management.loadbalancer.server.port=80"
      networks:
        - hindustan_applications

  socketio_salary_management:
    build:
      context: ..
      dockerfile: socketio_manager/Dockerfile
    hostname: socketio_salary_management
    container_name: socketio_salary_management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socketio_salary_management.rule=Host(`socketio.localhost`)"
      - "traefik.http.services.socketio_salary_management.loadbalancer.server.port=80"
    networks:
      - hindustan_applications

networks:
  hindustan_applications:
    external: true