version: "3.8"

services:

  backend:
      build:
        context: ..
        dockerfile: app/Dockerfile
      hostname: backend
      container_name: backend
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
        - "traefik.http.services.backend.loadbalancer.server.port=80"
      networks:
        - hindustan_applications

  socketio:
    build:
      context: ..
      dockerfile: socketio_manager/Dockerfile
    hostname: socketio
    container_name: socketio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socketio.rule=Host(`socketio.localhost`)"
      - "traefik.http.services.socketio.loadbalancer.server.port=80"
    networks:
      - hindustan_applications

networks:
  hindustan_applications:
    external: true