version: "3.8"

services:
  backend_salary_management:
    hostname: backend_salary_management-staging
    container_name: backend_salary_management_staging
    labels:
      - "traefik.http.routers.backend_salary_management.rule=Host(`backend-salary.zuvatech.com`)"
      - "traefik.http.routers.backend_salary_management.entrypoints=websecure"
      - "traefik.http.routers.backend_salary_management.tls.certresolver=myresolver"


  socketio_salary_management:
    hostname: socketio_salary_management-staging
    container_name: socketio_salary_management_staging
    labels:
      - "traefik.http.routers.socketio_salary_management.rule=Host(`socketio-salary.zuvatech.com`)"
      - "traefik.http.routers.socketio_salary_management.entrypoints=websecure"
      - "traefik.http.routers.socketio_salary_management.tls.certresolver=myresolver"
