version: "3.8"

services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--log.level=INFO"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  backend:
    build: .
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      mongodb: {}
      rabbitmq:
        condition: service_healthy
      minio: {}
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - web

  socketio:
    build: .
    # command: uvicorn socketio_manager.main:SocketServer --reload --port 9000 --host 0.0.0.0
    depends_on:
      - mongodb
      - rabbitmq
      - minio
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socketio.rule=Host(`socketio.localhost`)"
      - "traefik.http.services.socketio.loadbalancer.server.port=9000"
    networks:
      - web

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: zuvaLabs

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongodb.rule=Host(`mongo.localhost`)"
      - "traefik.http.services.mongodb.loadbalancer.server.port=27017"
    networks:
      - web

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: unless-stopped
    ports:
      - 5672:5672 # RabbitMQ default port
      - 15672:15672 # RabbitMQ management console port
      - 15674:15674 # RabbitMQ STOMP port

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist data
    environment:
      - RABBITMQ_DEFAULT_USER=root # Set the desired username
      - RABBITMQ_DEFAULT_PASS=zuvaLabs # Set the desired password
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management
      - RABBITMQ_PLUGINS=rabbitmq_web_stomp

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
    networks:
      - web

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: zuvaLabs
    command: server /data --console-address ":9090"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.localhost`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9090"
    networks:
      - web

volumes:
  mongo_data:
  rabbitmq_data:
  minio_data:

networks:
  web:
    driver: bridge