version: '3.8'

services:
  mongodb:
    labels:
      - "traefik.http.routers.mongodb.rule=Host(`mongo-salary.zuvatech.com`)"
    container_name: mongodb_staging

  rabbitmq:
    labels:
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq-salary.zuvatech.com`)"
    container_name: rabbitmq_staging

  minio:
    labels:
      - "traefik.http.routers.minio-api.rule=Host(`api.minio.zuvatech.com`)"
      - "traefik.http.routers.minio-console.rule=Host(`console.minio.zuvatech.com`)"

    container_name: minio_staging
