version: "3.8"

services:
  traefik:
    container_name: traefik_staging
    hostname: traefik-staging
    ports:
      - "80:80"
      - "443:443" # HTTPS port
      - "8080:8080" # Traefik dashboard (optional, for monitoring)
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true" # Consider securing this in production
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # Avoid exposing containers by default
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=jpranesh14@gmail.com" # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik-salary.zuvatech.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - "./letsencrypt:/letsencrypt" # Mount for Let's Encrypt storage
